### ISSUE TITLE
Screen behind "Achievements" popdown bleeds though

### ISSUE THREAD

**Issue by DavidPostill** [shu8/SE_OptionalFeatures#10]
This doesn't happen if Optional Features is disabled

Before popdown:

![screenshot - 18_07_2015 17_59_52](https://cloud.githubusercontent.com/assets/7079224/8762642/cfb5b17a-2d76-11e5-900e-13910b6e483a.png)

After popdown:

![screenshot - 18_07_2015 17_58_52](https://cloud.githubusercontent.com/assets/7079224/8762639/bf7ca890-2d76-11e5-927b-350f45346d57.png)

Settings:

> "Options saved: grayOutVotes,renameChat,exclaim,employeeStar,bulletReplace,addEllipsis,moveCommentsLink,fixedTopbar,highlightQuestions,colorAnswerer,kbdAndBullets,editComment,shareLinksMarkdown,commentShortcuts,quickCommentShortcutsMain,spoilerTip,commentReplies,parseCrossSiteLinks,linkQuestionAuthorName,sortByBountyAmount,isQuestionHot,autoShowCommentImages,showCommentScores,answerTagsSearch,titleEditDiff,metaNewQuestionAlert,betterCSS,standOutDupeCloseMigrated,editReasonTooltip,addSBSBtn" features.user.js:1112:9

**Comment by shu8** [comment]
@DavidPostill you seriously need to calm down :P 

It (again) only appears when you have fixed topbar enabled.

It happens because the class `label` for those icons has a `z-index` of `1`. If I remove that `z-index` - it causes the icon to go underneath the progress bar and I have no idea how to counteract that z-index.

Sorry - I'll put this on 'help-wanted' to see if anybody sees this - but unfortunately I don't know how to fix this :(

**Comment by DavidPostill** [comment]
Never mind. It's only cosmetic and only happens on profile pages.;) I'm just glad I checked disabling Optional Features, I was in the middle of reporting a bug on meta when I thought to check ... :/

**Comment by shu8** [comment]
@DavidPostill lol - normally the first suggestion when people can repro is 'any userscripts?' - so you'd have been in safe hands :)

**Comment by shu8** [comment]
@DavidPostill @Loxos fixed this! :)
