### ISSUE TITLE
On Ask Ubuntu, the topbar position is borked

### ISSUE THREAD

**Issue by eyeballcode** [shu8/SE_OptionalFeatures#11]
![](http://i.stack.imgur.com/dVWIr.png)

Also, the post content moves to the left when you scroll down.
The vote buttons cover the comments

![](https://cloud.githubusercontent.com/assets/6756003/8898024/ce9e1e7c-3450-11e5-869a-e74d84b55109.png)

**Comment by shu8** [comment]
> The post content moves to the left when you scroll down/The vote buttons cover the comments

I know about this 'bug' but have never been able to properly reproduce it. It 'just happens' at random, seemingly unsimilar times. However, a quick scroll up and down normally fixes this.

> Topbar position is borked

This only happens on Ask Ubuntu due to it having its own header at the top of the screen and a weird left/right margin. Honestly, it's just an awkward site - so I'm not going to fix it. You (or anybody else!) are welcome to submit a pull request to do a check on which site it is, and modify the CSS for the topbar, but IMHO it's a bit too much effort to fix for a single site.

**Comment by eyeballcode** [comment]
Ok, here's a fix I made
https://github.com/TeamFreeHugs/teamfreehugs.github.io/blob/master/stackexchange/userscripts/AskubuntuStickyToolbar.user.js

**Comment by shu8** [comment]
@eyeballcode cheers :) adding now, testing on AskUbuntu!

**Comment by shu8** [comment]
@eyeballcode  pushed to 1.6 DEV - please update :)

**Comment by shu8** [comment]
but for the record... that could have beeen muuuuuuuuuuch easier with jQuery!
