### ISSUE TITLE
Does nothing on Firefox 39.0

### ISSUE THREAD

**Issue by marki555** [shu8/SE_OptionalFeatures#7]
Hi, I tried to install both stable and dev version. Both of them installed fine, I can see as active it when I click Greasemonkey icon on toolbar, however nothing happens - I don't get the "add features" menu added. I tried looking at Web Developer Console, but don't see there any error related to it, only these two when loading https://stackoverflow.com:

`22:11:37.918 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.1 jquery.min.js:3:0`
`22:11:37.948 Firefox can't establish a connection to the server at wss://qa.sockets.stackexchange.com/.1 full.en.js:1:0`

In the FF profile folder I see the GM script downloaded with few other files:
`68269 features.user.js`
`200719 jquery-ui.min.js`
`6580 jquery.feeds.js`
`5017 jquery.hotkeys.js`
`4896 jquery.stickyelement.js`
`12822 rangyinputs-jquery-src.js`

How can I further troubleshoot it?

**Comment by shu8** [comment]
@marki555 I'm not sure why it doesn't work - the link to add features should appear. One thing you can try:

On line 1061 (just above (`$(function() {`), add `console.log('before');` and on line 1063 (just after (`$(function() {`), add `console.log('after')`. Then go to SO's homepage, refresh and see what appears in the console. Please tell me what you see :)

**Comment by marki555** [comment]
No change on the console, I don't see any of before/after. But Greasemonkey icon says it is enabled and lists the script on stackoverflow as active and enabled. (Other GM scripts on other websites work without issues).

**Comment by shu8** [comment]
@marki555 I just installed Firefox and can repro this issue. I tried installing in Firefox, it didn't work. I tried installing in a new Chrome profile, it worked. I can't, at the moment, see the problem. I'll look into it and ping you as soon as it's fixed. Thanks for informing me!

I don't understand why it doesn't log anything in the console, as if the script isn't running - but GM says it is!! I'm extremely baffled! But I'll try to see what's happening :)

**Comment by shu8** [comment]
@marki555 I've updated the script - can you please reinstall and check it out? :)

**Comment by shu8** [comment]
I think the problem was jQuery not loading properly, so I added the code from jQuery's website rather than google's cdn. BTW it seems there's a difference between the console we were looking at and the window that pops up when you press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> - where the actual errors appear...

**Comment by marki555** [comment]
Thanks, now it seems to work. It showed the config dialog on first load, but then I don't see any button anywhere where I could show it again.
Also on 2nd reload it showed dialog box to add my own edit reasons, but the button there did nothing, also Close did nothing. I had to click Reset in the top left to get rid of this dialog.
Also side-by-side editing works only for new answers, not for editing questions/answers. Is this by design?

**Comment by shu8** [comment]
@marki555 
- You should be able to see the `add features` link at the top right of any profile (doesn't even have to be your own)
- Yeah - that's kind of a bug - you must reset, _at the beginning_, the edit reasons - I might try to change that so that the default options are saved at the beginning automatically!
- Yep, side-by-side editing only works on new answers or new questions. **Although**, I am working on it for edits - it's just that the CSS for answers/questions doesn't work for edits. **As a workaround**, till then, when editing, instead of using the inline-editing, just CTRL+CLICK the `edit` button, causing it to open in a new tab, like it did before you get the 2k editing privilege. You will see the SBS button here, and will be able to _edit_ side-by-side.

Please do tell me if you still can't see the `add features` button, and I'll try to find out the reason. If you can't see it, please click Ctrl+Shift+J to open the console 'thing' and tell me if you see anything weird there. Thanks a lot!

**Comment by marki555** [comment]
Yes, I now see the "add features" link. So it seems everything is working now, thanks.

**Comment by shu8** [comment]
@marki555  yay! Closing this issue now :)

BTW if you add an issue to fix the edit reasons bug, I'll be happy to look at it :)
